main: de.timesnake.basic.bukkit.core.main.BasicBukkit
version: 3.5.0
name: basic-bukkit
author: timesnake
softdepend: [ database-bukkit, channel-bukkit ]
api-version: 1.13

commands:

  pp:
    aliases:
      - privacy
      - privacypolicy


  global:
    aliases:
      - all
      - g

  pid:

  logger:
    aliases:
      - log

  password:
    aliases:
      - pwd

  code:
     