main: de.timesnake.basic.bukkit.core.main.BasicBukkit
version: 1.0
name: basic-bukkit
author: Mn
depend: [ database-bukkit ]
api-version: 1.13

commands:

  ban:
  tmpban:
  tempban:
  unban:
  pardon:
  kick:
  mute:
  unmute:

  netban:
  nettmpban:
  nettempban:
  netunban:
  netpardon:
  netkick:
  netmute:
  netunmute:

  dpd:
  dataprotection:
  datadeclaration:
  datapd:
  dpdeclaration:

  channelmsg:
  channelmsgs:
  channelmessages:
  channelmessage:

  worlds:
  world:
  ws:
  w:

  databasemsg:
  databasemsgs:
  databasemessage:
  databasemessages:

  packetsmsg:
  packetsmsgs:
  packetsmessage:
  packetsmessages:

  global:
  g:

  pid:

  log:
  logger:
     